spring:
  application:
    name: tradecore

  datasource:
    url: jdbc:postgresql://localhost:5432/tradecore
    username: tradecore_user
    password: TradeCore2026
    driver-class-name: org.postgresql.Driver